# SwiftLint Configuration for Merlin Clash iOS

# 包含的路径
included:
  - MerlinClash

# 排除的路径
excluded:
  - Pods
  - Carthage
  - .build
  - DerivedData

# 禁用的规则
disabled_rules:
  - trailing_whitespace
  - line_length

# 启用的可选规则
opt_in_rules:
  - empty_count
  - empty_string
  - explicit_init
  - first_where
  - sorted_imports
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces

# 规则配置
line_length:
  warning: 120
  error: 150
  ignores_comments: true
  ignores_urls: true

file_length:
  warning: 500
  error: 1000

function_body_length:
  warning: 50
  error: 100

type_body_length:
  warning: 300
  error: 500

cyclomatic_complexity:
  warning: 10
  error: 20

nesting:
  type_level:
    warning: 2
  statement_level:
    warning: 5

identifier_name:
  min_length:
    warning: 2
  max_length:
    warning: 50
  excluded:
    - id
    - url
    - URL

type_name:
  min_length: 3
  max_length: 50

# 自定义规则
custom_rules:
  # 强制使用 self
  explicit_self:
    name: "Explicit Self"
    regex: '(?<!self\.)(?:init|deinit)\('
    message: "Use explicit self when calling init or deinit"
    severity: warning

  # 避免使用强制解包
  force_unwrapping:
    name: "Force Unwrapping"
    regex: '!\s*(?!\/\/)'
    message: "Avoid using force unwrapping"
    severity: warning

# 报告格式
reporter: "xcode"
